name: Sync Leetcode

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: LqJO8uZcEgOSIf0hldnEejQke2YXGxLx7pN5WSMJ8BptKaL9RtBE7aF3zBXUDSkS
          leetcode-session: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNTkxOTcxMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjhmNWIwNGExNWU1NzczNDQ0NjFiNGQ0NjNkMDgxZTU4NWIxMDMyZTZkNmRlZTFkMTU4NTdhZTk3YjI1OGYyMGUiLCJpZCI6NTkxOTcxMywiZW1haWwiOiJ2aXJlbmRyYXBhdGlsLjI0dnBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ2aXJlbmRyYXBhdGlsMjQiLCJ1c2VyX3NsdWciOiJ2aXJlbmRyYXBhdGlsMjQiLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvYXZhdGFycy9hdmF0YXJfMTY2MDM3NjIxMS5wbmciLCJyZWZyZXNoZWRfYXQiOjE3MTAyNjI3NzUsImlwIjoiNDUuMTE3LjcyLjYiLCJpZGVudGl0eSI6IjI0ZTg3ZTVmMTU2YWI0OGM1YmI1NTllNGMxNjUyMjM0Iiwic2Vzc2lvbl9pZCI6NTQ5NDkwMjUsIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.bCoda5ESp48xRPavzsUWAoBlRU_Zc_O1tu7-CJdzZkQ
          destination-folder: leetcode
