name: Sync Leetcode

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: mEVkm7LlnY4ZrgaLOAMvCb1Msw35iNLMMaaFbXk9FA9noQxps9FSBa57ZKD4N4sk
          leetcode-session: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNTkxOTcxMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjhmNWIwNGExNWU1NzczNDQ0NjFiNGQ0NjNkMDgxZTU4NWIxMDMyZTZkNmRlZTFkMTU4NTdhZTk3YjI1OGYyMGUiLCJpZCI6NTkxOTcxMywiZW1haWwiOiJ2aXJlbmRyYXBhdGlsLjI0dnBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ2aXJlbmRyYXBhdGlsMjQiLCJ1c2VyX3NsdWciOiJ2aXJlbmRyYXBhdGlsMjQiLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvdmlyZW5kcmFwYXRpbDI0L2F2YXRhcl8xNzE2ODI4NDMwLnBuZyIsInJlZnJlc2hlZF9hdCI6MTcyMDE1MTAyMiwiaXAiOiIxMDMuMTc4LjIxMy4yNTIiLCJpZGVudGl0eSI6IjEwZjkyODdkZWFmNjA5ZWUzNmZiMzc3ODNmMmI4OWMwIiwiZGV2aWNlX3dpdGhfaXAiOlsiNWFjNWUwZWQ5NmEzNzA1MzQ5NjlhZTY2MTM4NTY0YmMiLCIxMDMuMTc4LjIxMy4yNTIiXSwic2Vzc2lvbl9pZCI6NjQ4ODk2NzgsIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.gBaoJ83aGhT91EoZpwWB_tFPxmwVNdK8T_CQb-dXqyc
          destination-folder: leetcode
