name: Sync Leetcode

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: aDqrMu9cGgm4b5xl3QS3bM1WCbRAj4yCkQnAvX3hhbDTauukxfusJp7esZuSnYdb
          leetcode-session: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNTkxOTcxMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjhmNWIwNGExNWU1NzczNDQ0NjFiNGQ0NjNkMDgxZTU4NWIxMDMyZTZkNmRlZTFkMTU4NTdhZTk3YjI1OGYyMGUiLCJpZCI6NTkxOTcxMywiZW1haWwiOiJ2aXJlbmRyYXBhdGlsLjI0dnBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJ2aXJlbmRyYXBhdGlsMjQiLCJ1c2VyX3NsdWciOiJ2aXJlbmRyYXBhdGlsMjQiLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvdmlyZW5kcmFwYXRpbDI0L2F2YXRhcl8xNzE2ODI4NDMwLnBuZyIsInJlZnJlc2hlZF9hdCI6MTczNzQzODE5NSwiaXAiOiIyNDAxOjQ5MDA6MWM3ZTo4NmJmOjM5MjA6NmNhZjpmZWVkOjNmZmUiLCJpZGVudGl0eSI6IjA4NDViMzA5YzdiOWI5NTdhZmQ5ZWNmNzc1YTRjMjFmIiwiZGV2aWNlX3dpdGhfaXAiOlsiODI4ZWIxMmY4ZTIzNjJjYzA2NjExMWZhM2EzODNiMTUiLCIyNDAxOjQ5MDA6MWM3ZTo4NmJmOjM5MjA6NmNhZjpmZWVkOjNmZmUiXSwic2Vzc2lvbl9pZCI6MjI2NjMwNSwiX3Nlc3Npb25fZXhwaXJ5IjoxMjA5NjAwfQ.uN9gOy49uw8HYDd6lKcmdbZrmHAmW8AfpnTJ_X9n0oM
          destination-folder: leetcode
 
