name: Sync Leetcode

on:
  schedule:
    - cron: "30 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: k4UgM4usOZ16yjfhVzA6rlmcPetH8HAmmqRouK5DhULHJW7S3ZnfypuDs00t1NwW
          leetcode-session: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNTkxOTcxMyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjhmNWIwNGExNWU1NzczNDQ0NjFiNGQ0NjNkMDgxZTU4NWIxMDMyZTZkNmRlZTFkMTU4NTdhZTk3YjI1OGYyMGUiLCJzZXNzaW9uX3V1aWQiOiJmNTNlMmI3YiIsImlkIjo1OTE5NzEzLCJlbWFpbCI6InZpcmVuZHJhcGF0aWwuMjR2cEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZpcmVuZHJhcGF0aWwyNCIsInVzZXJfc2x1ZyI6InZpcmVuZHJhcGF0aWwyNCIsImF2YXRhciI6Imh0dHBzOi8vYXNzZXRzLmxlZXRjb2RlLmNvbS91c2Vycy92aXJlbmRyYXBhdGlsMjQvYXZhdGFyXzE3MTY4Mjg0MzAucG5nIiwicmVmcmVzaGVkX2F0IjoxNzQwNDk2MjY0LCJpcCI6IjI0MDE6NDkwMDo3OWQ5OjRjNGY6Nzk4NzpjNWZiOmJiMTY6OWQ1MyIsImlkZW50aXR5IjoiYjgwMWQ0OTRmMTIyNzkzYjA2MTI2MzZiZmEyMzRiOWMiLCJkZXZpY2Vfd2l0aF9pcCI6WyIxMjJmMGIzNmY2ZTMyY2JmZDJhODI2NmUwMTJhODliOSIsIjI0MDE6NDkwMDo3OWQ5OjRjNGY6Nzk4NzpjNWZiOmJiMTY6OWQ1MyJdLCJfc2Vzc2lvbl9leHBpcnkiOjEyMDk2MDB9.hcURarPni_txz58vDYnTYJxBXwn22h7-Qfqt116P2As
          destination-folder: leetcode
 
